PracaMGR/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;
using PracaMGR.ViewModels;

namespace PracaMGR.Controllers
{
    public class ForumController : Controller
    {
        JakTraficEntities data = new JakTraficEntities();

        // GET: Forum
        public ActionResult Index(int page = 1)
        {
            var list = new List<Kategorie>(data.Kategorie);
            IPagedList<Kategorie> li = list.ToPagedList(page, 10);

            return View(li);
        }

        public ActionResult Linie(int page = 1)
        {
            var list = new List<LiniaViewModel>();
            
            foreach (var a in data.Linie)
            {
                double suma = 0;
                int licz = 0;
                foreach (var b in data.Oceny)
                {
                    if (a.Symbol.Equals(b.Symbol_linii)) { suma = suma + b.Suma; licz++; }
                }
                var c = new LiniaViewModel { Record = a, Ocena = licz > 0 ? Math.Round(suma / (double)licz, 2) : 0 };

                list.Add(c);
            }
            IPagedList<LiniaViewModel> li = list.ToPagedList(page, 10);      

            return View(li);
        }

        [Authorize]
        public ActionResult Ocena(String id)
        {
            var a = new Oceny { Symbol_linii = id };
            return View(a);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Ocena(String id, FormCollection collection)
        {
            try
            {
                var a = new Oceny();               
                UpdateModel(a);

                a.Symbol_linii = id;
                a.Uzytkownik = User.Identity.Name;
                var ss = Math.Round((double)(a.Punktualnosc+a.Poczucie_bezpieczenstwa+a.Kultura_os_kierowcy+a.Komfort_jazdy+a.Czystosc)/5,2);
                a.Suma = ss; 
           
                data.Oceny.Add(a);
                data.SaveChanges();

                return RedirectToAction("Linie");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: Forum/Create
        public ActionResult Create()
        {            
                return View();           
        }

        // POST: Forum/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var a = new Kategorie();
                UpdateModel(a);
                data.Kategorie.Add(a);
                data.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Forum/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            Kategorie a = data.Kategorie.Single(i => i.Id == id);
            return View(a);
        }

        // POST: Forum/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                var a = data.Kategorie.Single(i => i.Id == id);
                UpdateModel(a);
                data.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Kategorie a = data.Kategorie.Single(i => i.Id == id);
            return View(a);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                Kategorie a = data.Kategorie.Single(i => i.Id == id);  
                
                data.Odpowiedzi.RemoveRange((from f in data.Odpowiedzi
                                                   from d in data.Posty
                                                   where d.Id_kategoria == id && f.Id_Post == d.Id
                                                   select f).Distinct());
                data.Posty.RemoveRange(from f in data.Posty
                                             where f.Id_kategoria == id
                                             select f);

                data.Kategorie.Remove(a);
                data.SaveChanges();
                

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PracaMGR/Controllers/PostyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PracaMGR;
using PracaMGR.Models;

namespace Praca.Controllers
{
    public class PostyController : Controller
    {
        JakTraficEntities data = new JakTraficEntities();

        // GET: Posty      
        public ActionResult Index(int id, int page = 1)
        {
            TempData["kategoria"] = id;
           
            var list = new List<Posty>(from a in data.Posty
                                       where a.Id_kategoria.Equals(id) 
                                       orderby a.Data descending
                                       select a);

            IPagedList<Posty> li = list.ToPagedList(page,10);
            return View(li);
        }

        public ActionResult Odpowiedzi(int id,int page = 1)
        {
            var a = new Post { post = data.Posty.Single(i => i.Id == id) };
            var li = data.Odpowiedzi.Where(item => item.Id_Post.Equals(id)).ToList();
            li.Reverse();
            a.odpowiedz = li.ToPagedList(page, 10); 
            return View(a);
        }

        [HttpPost]
        [Authorize(Roles = "SimpleUser,Admin")]
        public ActionResult Dodaj(String tresc, int post)
        {
            var a = new Odpowiedzi { Id_Post = post, Data = DateTime.Now, Tresc = tresc, Uzytkownik = User.Identity.Name };
            data.Odpowiedzi.Add(a);
            data.SaveChanges();

            return RedirectToAction("Odpowiedzi/" + post);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "SimpleUser,Admin")]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                String g = TempData["kategoria"].ToString();
                var a = new Posty {Id_kategoria = int.Parse(g), Data = DateTime.Now, Uzytkownik = User.Identity.Name};
                UpdateModel(a);
                data.Posty.Add(a);
                data.SaveChanges();

                return RedirectToAction("Index/"+int.Parse(g));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            return View(data.Posty.FirstOrDefault(x => x.Id == id));
        }

        [HttpPost]
        [Authorize(Roles = "SimpleUser,Admin")]
        public ActionResult Edit(FormCollection collection)
        {
            try
            {
                int id = int.Parse(collection["Id"].ToString());
                var a = data.Posty.FirstOrDefault(x => x.Id == id);
                UpdateModel(a);              
                data.SaveChanges();

                return RedirectToAction("Index/" + a.Id_kategoria);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            Posty a = data.Posty.Single(i => i.Id == id);
            return View(a);
        }

        [HttpPost]
        [Authorize(Roles = "SimpleUser,Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {             
                String g = TempData["kategoria"].ToString();
                Posty a = data.Posty.Single(i => i.Id == id);
                if (User.Identity.Name == a.Uzytkownik || User.IsInRole("Admin"))
                {
                    data.Odpowiedzi.RemoveRange(from b in data.Odpowiedzi where b.Id_Post == id select b);
                    data.Posty.Remove(a);
                    data.SaveChanges();

                    return RedirectToAction("Index/" + int.Parse(g));
                }
                else
                {
                    return new HttpUnauthorizedResult();
                }
            }
            catch
            {
                String g = TempData["kategoria"].ToString();
                return RedirectToAction("Index/" + int.Parse(g));
            }
        }

        public ActionResult EditAnswer(int id)
        {
            Odpowiedzi a = data.Odpowiedzi.Single(i => i.Id == id);
            return View(a);
        }

        [HttpPost]
        public ActionResult EditAnswer(FormCollection collection)
        {
            try
            {
                int id = int.Parse(collection["Id"].ToString());
                var a = data.Odpowiedzi.FirstOrDefault(x => x.Id == id);
                UpdateModel(a);
                data.SaveChanges();

                return RedirectToAction("Odpowiedzi/" + a.Id_Post);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public ActionResult DeleteAnswer(int id)
        {
             var odpowiedz = data.Odpowiedzi.SingleOrDefault(x => x.Id == id);
             
             if (odpowiedz != null)
             {
                 int id_post = odpowiedz.Id_Post;
                 if (User.Identity.Name == odpowiedz.Uzytkownik || User.IsInRole("Admin"))
                 {
                     data.Odpowiedzi.Remove(odpowiedz);
                     data.SaveChanges();

                     return RedirectToAction("Odpowiedzi", new { id = id_post });
                 }
                 else
                 {
                     return new HttpUnauthorizedResult();
                 }
             }
             else
             {
                 return View("Error");
             }
         }
    }
}

PracaMGR/Views/Forum/Create.cshtml
@model PracaMGR.Kategorie

@{
    ViewBag.Title = "Utwórz";
}

<h2>Nowa Kategoria</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kategorie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Nazwa, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "Index", null, new { @class = "btn btn-default" })
</div>

PracaMGR/Views/Forum/Delete.cshtml
@model PracaMGR.Kategorie

@{
    ViewBag.Title = "Usuń";
}

<h2>Usuwanie Kategorii</h2>
<br />
<h3>Na pewno chcesz usunąć tą Kategorie?</h3>
<div>
    @*<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

    </dl>*@

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" />
            @Html.ActionLink("Wróć", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

PracaMGR/Views/Forum/Edit.cshtml
@model PracaMGR.Kategorie

@{
    ViewBag.Title = "Edytuj";
}

<h2>Edytuj Kategorie</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kategorie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Nazwa, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
                @Html.ActionLink("Wróć", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

PracaMGR/Views/Forum/Index.cshtml
@using PagedList
@using PagedList.Mvc

@model IPagedList<PracaMGR.Kategorie>



    @{
        ViewBag.Title = "Kategorie";
    }

    <h2>Wybierz Kategorie...</h2>

    @if (User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("Utwórz nową kategorię", "Create", null, new { @class = "btn btn-default" })
        </p>
    }

    <table class="table">
        <tr>
            <th>
                Nazwa
            </th>
            <th></th>
        </tr>
        <tr>
            <td>
                Ocena Linii Autobusowych
            </td>
            <td>
                @Html.ActionLink("Oceniaj...", "Linie", null, new { @class = "btn btn-default" })
            </td>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nazwa)
                </td>
                <td>
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })
                        @Html.ActionLink("Usuń", "Delete", new { id = item.Id }, new { @class = "btn btn-default" })
                    }
                    @Html.ActionLink("Przeglądaj", "Index","Posty", new { id = item.Id }, new { @class = "btn btn-default" })                  

                </td>
            </tr>
        }

    </table>

    <div class="pagedList">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { Model, page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
    </div>

PracaMGR/Views/Forum/Linie.cshtml
@using PagedList
@using PagedList.Mvc

@model IPagedList<PracaMGR.ViewModels.LiniaViewModel>

@{
    ViewBag.Title = "Linie";
}

<h2>Linie autobusowe</h2>
<br />
<table class="table table-responsive">
    <tr>
        <th>
            Symbol linii
        </th>
        <th>
            Średnia ocen
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Record.Symbol)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ocena)
        </td>
        <td>
            @Html.ActionLink("Dodaj Ocenę", "Ocena", new { id = item.Record.Symbol }, new { @class = "btn btn-default" })
        </td>
    </tr>
}

</table>

<div class="pagedList">
    @Html.PagedListPager(Model, page => Url.Action("Linie", new { Model, page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
</div>

PracaMGR/Views/Forum/Ocena.cshtml
@model PracaMGR.Oceny

@{
    ViewBag.Title = "Ocena";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
<script src="~/Scripts/jquery-1.10.2.js"></script>



<h2>Oceniaj linie autobusowe</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Oceny</h4>
        <hr />    
            <div class="grupa">
                <p>
                    <label for="Punktualnosc">Punktualność:</label>
                    <input type="text" id="Punktualnosc" name="Punktualnosc" style="font-size: 20px; border: 0; background-color: transparent; color: #000000; font-weight: bold;">
                </p>
                <div id="punktualnosc" style="width: 60%;"></div>
                <br />
                <p>
                    <label for="Czystosc">Czystość:</label>
                    <input type="text" id="Czystosc" name="Czystosc" style="font-size: 20px; border: 0; background-color: transparent; color: #000000; font-weight: bold;">
                </p>
                <div id="czystosc" style="width: 60%;"></div>
                <br />
                <p>
                    <label for="Kultura_os_kierowcy">Kultura osobista kierowcy:</label>
                    <input type="text" id="Kultura_os_kierowcy" name="Kultura_os_kierowcy" style="font-size: 20px; border: 0; background-color: transparent; color: #000000; font-weight: bold;">
                </p>
                <div id="kultura" style="width: 60%;"></div>
                <br />
                <p>
                    <label for="Komfort_jazdy">Komfort Jazdy:</label>
                    <input type="text" id="Komfort_jazdy" name="Komfort_jazdy" style="font-size: 20px; border: 0; background-color: transparent; color: #000000; font-weight: bold;">
                </p>
                <div id="komfort" style="width: 60%;"></div>
                <br />
                <p>
                    <label for="Poczucie_bezpieczenstwa">Poczucie bezpieczeństwa:</label>
                    <input type="text" id="Poczucie_bezpieczenstwa" name="Poczucie_bezpieczenstwa" style="font-size: 20px; border: 0; background-color: transparent; color: #000000; font-weight: bold;">
                </p>
                <div id="bezpieczenstwo" style="width: 60%;"></div>
                <br />              
                <input type="submit" id="area1" value="Oceń" class="btn btn-default" />
                @Html.ActionLink("Wróć", "Linie", null, new { @class = "btn btn-default", id = "area1" })
                <br />
            </div>
        </div>
}
<br />

@section scripts {

    <script type="text/javascript">
        $(function() {
            $("#punktualnosc").slider({
                range: "max",
                min: 0,
                max: 10,
                value: 5,
                slide: function(event, ui) {
                    $("#Punktualnosc").val(ui.value);
                }
            });
            $("#Punktualnosc").val($("#punktualnosc").slider("value"));
        });

        $(function() {
            $("#czystosc").slider({
                range: "max",
                min: 0,
                max: 10,
                value: 5,
                slide: function(event, ui) {
                    $("#Czystosc").val(ui.value);
                }
            });
            $("#Czystosc").val($("#czystosc").slider("value"));
        });

        $(function() {
            $("#kultura").slider({
                range: "max",
                min: 0,
                max: 10,
                value: 5,
                slide: function(event, ui) {
                    $("#Kultura_os_kierowcy").val(ui.value);
                }
            });
            $("#Kultura_os_kierowcy").val($("#kultura").slider("value"));
        });

        $(function() {
            $("#komfort").slider({
                range: "max",
                min: 0,
                max: 10,
                value: 5,
                slide: function(event, ui) {
                    $("#Komfort_jazdy").val(ui.value);
                }
            });
            $("#Komfort_jazdy").val($("#komfort").slider("value"));
        });

        $(function() {
            $("#bezpieczenstwo").slider({
                range: "max",
                min: 0,
                max: 10,
                value: 5,
                slide: function(event, ui) {
                    $("#Poczucie_bezpieczenstwa").val(ui.value);
                }
            });
            $("#Poczucie_bezpieczenstwa").val($("#bezpieczenstwo").slider("value"));
        });
    </script>
}